# Generated by Django 3.2.3 on 2021-05-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='coupon',
            field=models.ManyToManyField(null=True, through='users.UserCoupon', to='users.Coupon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kakao',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='kakao_account',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='kakao_email',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='kakao_nickname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='marketing_agree',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_url',
            field=models.URLField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='refund_account',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
