# Generated by Django 3.2.3 on 2021-05-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210526_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='kakao',
            new_name='kakao_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='marketing_agree',
            new_name='marketing_agreement',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kakao_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kakao_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kakao_nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
