# Generated by Django 3.2.3 on 2021-05-26 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('taxi_code', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('location_code', models.CharField(max_length=20)),
                ('image_url', models.URLField(default='', max_length=2000)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('sale_rate', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'seat_types',
            },
        ),
        migrations.CreateModel(
            name='TaxiCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('logo_url', models.URLField(default='', max_length=2000)),
            ],
            options={
                'db_table': 'taxi_companies',
            },
        ),
        migrations.CreateModel(
            name='TaxiDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('profile_url', models.URLField(default='', max_length=2000)),
                ('introduction', models.CharField(max_length=2000)),
                ('taxi_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxis.taxicompany')),
            ],
            options={
                'db_table': 'taxi_drivers',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=13)),
                ('seat_remain', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxis.course')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxis.seattype')),
                ('taxi_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxis.taxidriver')),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='DriverReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=2000)),
                ('taxi_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxis.taxidriver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'driver_reviews',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='arrival_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_location', to='taxis.location'),
        ),
        migrations.AddField(
            model_name='course',
            name='departure_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_location', to='taxis.location'),
        ),
        migrations.AddField(
            model_name='course',
            name='taxi_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxis.taxicompany'),
        ),
    ]
