# Generated by Django 3.2.3 on 2021-05-26 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='arrival_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='taxis.location'),
        ),
        migrations.AlterField(
            model_name='course',
            name='departure_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='taxis.location'),
        ),
    ]
